---
- name: Wipe existing web application container and files
  block:
    - name: Stop web application container using docker-compose
      shell: docker-compose -f /opt/web_app/docker-compose.yml down
      args:
        chdir: /opt/web_app
      tags:
        - wipe

    - name: Remove docker-compose file
      file:
        path: /opt/web_app/docker-compose.yml
        state: absent
      tags:
        - wipe
  when: web_app_full_wipe
