networks:
  loki:

x-logging:
  &my-logging
  driver: "json-file"
  options:
    max-size: "200k"
    max-file: "10"
    tag: "{{.ImageName}}|{{.Name}}"

x-deploy:
  &my-deploy
  resources:
    limits:
      memory: 512M

services:
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging: *my-logging
    deploy: *my-deploy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    logging: *my-logging
    deploy: *my-deploy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3101/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  moscow-time-app:
    container_name: moscow-time-app
    build:
      context: ../app_python
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - loki
    logging: *my-logging
    deploy: *my-deploy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8081/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  url_shortener:
    container_name: url_shortener
    build:
      context: ../app_go
      dockerfile: Dockerfile
      args:
        config_path: ./config/local.yaml
    ports:
      - "8080:8080"
    networks:
      - loki
    logging: *my-logging
    deploy: *my-deploy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/manage || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    logging: *my-logging
    deploy: *my-deploy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus.yml
    networks:
      - loki
    logging: *my-logging
    deploy: *my-deploy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9090/-/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
