global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: moscow-time-app
    static_configs:
      - targets: [ 'moscow-time-app:8081' ]

  - job_name: url_shortener
    static_configs:
      - targets: [ 'url_shortener:8080' ]

  - job_name: loki
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: promtail
    static_configs:
      - targets: [ 'promtail:9080' ]

  - job_name: grafana
    static_configs:
      - targets: [ 'grafana:3000' ]