name: url-shortener

on:
  push:
    branches:
      - "*"
    paths:
      - ".github/workflows/**"
      - "app_go/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - "app_go/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Lint the code
        run: gofmt -e ./app_go

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Run Tests
        run: cd app_go && go test -v ./...

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Run Snyk to Check for Vulnerabilities in Go code
        uses: snyk/actions/setup@master
      - run: cd app_go && snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  build:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./app_go
          file: ./app_go/distroless.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener-distroless:latest
          build-args: |
            config_path=./config/local.yaml

