name: moscow_time_app

on:
  push:
    branches:
      - "*"
    paths:
      - ".github/workflows/**"
      - "app_python/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - "app_python/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip

      - name: Install Dependencies
        run: pip install -r ./app_python/requirements.txt

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip

      - name: Install Dependencies
        run: pip install -r ./app_python/requirements.txt

      - name: Run Tests
        run: cd app_python && pytest ./tests

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip

      - name: Install Dependencies
        run: pip install -r ./app_python/requirements.txt

      - name: Run Snyk to Check for Vulnerabilities in Python Dependencies
        uses: snyk/actions/setup@master
      - run: cd app_python && snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./app_python/
          file: ./app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/moscow_time_app:latest


